repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black --config app/settings/.black .
        language: system
        types: [python]
        pass_filenames: false
      - id: autoflake
        name: autoflake
        entry: autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r .
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: make test
        language: system
        types: [ python ]
        pass_filenames: false